// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ithvwszzewlsaevuniaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0aHZ3c3p6ZXdsc2FldnVuaWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTExNzMsImV4cCI6MjA3MzE4NzE3M30.dwP1c6qdMpD5j708Tpy0nWO1MefiFpEVqdeG2rV-cXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});